apiVersion: v1
kind: PersistentVolume
metadata:
  name: ckad-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /tmp/ckad-pv
    type: DirectoryOrCreate