apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: five-volumes
  name: five-volumes
spec:
  containers:
  - command:
    - sh
    - -c
    - sleep 3600
    image: busybox
    name: five-volumes
    resources: {}
    volumeMounts:
    - name: empty-vol
      mountPath: /first
    - name: hostpath-vol
      mountPath: /second
    - name: pvc-vol
      mountPath: /third
    - name: cm-vol
      mountPath: /fourth
    - name: secret-vol
      mountPath: /five
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: empty-vol
    emptyDir: {}
  - name: hostpath-vol
    hostPath:
      path: /tmp/some-dir
      type: DirectoryOrCreate
  - name: pvc-vol
    persistentVolumeClaim:
      claimName: ckad-pvc
  - name: cm-vol
    configMap:
      name: ckad-cm-game
      items:
      - key: game.properties
        path: game.properties
      - key: user-interface.properties
        path: user-interface.properties
  - name: secret-vol
    secret:
      secretName: ckad-secret-vols
      items:
      - key: pass
        path: secret/pass-dir
status: {}
