apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod
spec:
  containers:
  - image: nginx:1.20.1
    name: readiness-pod
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 15
      periodSeconds: 5
