apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ckad-cm-pod
  name: ckad-cm-pod
spec:
  containers:
  - image: nginx:stable
    name: ckad-cm-pod
    resources: {}
    env:
    - name: SEBA
      valueFrom:
        configMapKeyRef:
          name: ckad-cm
          key: key1
    envFrom:
    - configMapRef:
        name: ckad-cm
      prefix: "CM_"
    volumeMounts:
    - name: config
      mountPath: /etc/ckad-cm
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: config
    configMap:
      name: ckad-cm
status: {}
