apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ckad-secret-pod
  name: ckad-secret-pod
spec:
  containers:
  - image: nginx
    name: ckad-secret-pod
    resources: {}
    env:
    - name: SEBA
      valueFrom:
        secretKeyRef:
          name: ckad-secret
          key: key1
    envFrom:
    - secretRef:
        name: ckad-secret
      prefix: CKAD_
    volumeMounts:
    - name: secret-vol
      readOnly: true
      mountPath: /etc/secret
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: secret-vol
    secret:
      secretName: ckad-secret
      items:
      - key: key2
        path: passwords/passwords.txt
