apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
spec:
  containers:
  - args:
    - sh
    - -c
    - echo $MESSAGE; cat /config/app.cfg
    image: busybox
    name: cm-pod
    resources: {}
    env:
    - name: MESSAGE
      valueFrom:
        configMapKeyRef:
          name: my-config-map
          key: message
    volumeMounts:
    - name: secrets
      mountPath: /config
  volumes:
  - name: secrets
    configMap:
      name: my-config-map
  restartPolicy: Never
