apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - args:
    - sh
    - -c
    - echo $SENSITIVE_STUFF; cat /config/passwords.txt
    image: busybox
    name: secret-pod
    resources: {}
    env:
    - name: SENSITIVE_STUFF
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: sensitive.data 
    volumeMounts:
    - name: secrets
      mountPath: /config
  volumes:
  - name: secrets
    secret:
      secretName: my-secret
      items:
      - key: passwords.txt
        path: passwords.txt
  restartPolicy: Never
