apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: list-pod-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-pod-role
subjects:
- kind: ServiceAccount
  name: my-sa
  namespace: default
