apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: config-vol
      mountPath: /etc/lala
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  volumes:
  - name: config-vol
    configMap:
      name: cmvolume
status: {}
