apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cpu-demo
  name: cpu-demo
spec:
  containers:
  - image: vish/stress
    name: cpu-demo
    args:
    - -cpus
    - "2"
    resources:
      requests:
        cpu: "0.5"
      limits:
        cpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
