apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: memory-demo
  name: memory-demo
spec:
  containers:
  - image: polinux/stress
    name: memory-demo
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
