/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import tutorial.Addressbook
import tutorial.person
import java.io.ByteArrayOutputStream

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val per = person {
        id = 1
        name = "Sebastian"
        email = "sss@example.com"
    }
    val out = ByteArrayOutputStream()
    per.writeTo(out)
    println(out)

    val ba = out.toByteArray()
    val per2 = Addressbook.Person.newBuilder().mergeFrom(ba).build()
    println(per2.email)
}
