apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: beehives.acloud.guru 
spec:
  group: acloud.guru
  names:
    plural: beehives
    singular: beehive
    kind: BeeHive
    shortNames:
    - hive 
  scope: Namespaced
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                supers:
                  type: integer
                bees:
                  type: integer