/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import dev.forkhandles.result4k.valueOrNull
import dev.forkhandles.values.ofResult4k

fun main() {
    val email = Email.of("example@example.com")
    println(email)
    try {
        Email.of("abc")
    } catch (x: IllegalArgumentException) {
        println("'abc' is invalid email address")
    }
    val notEmail = Email.ofResult4k("abc").valueOrNull()
    println(notEmail)

    val postalCode = PostalCode.of("88-310")
    println(postalCode)

    val orderId = OrderId.of(2)
    println(orderId)
}
