---
version: '2'
services:
  elasticsearch:
    image: elasticsearch:6.8.18
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node