apiVersion: v1
kind: Pod
metadata:
  name: resources-pod
spec:
  containers:
  - args:
    - sh
    - -c
    - while true; do echo Running...; sleep 5; done
    image: busybox
    name: resources-pod
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 128Mi
        cpu: 500m
