apiVersion: v1
kind: Pod
metadata:
  name: too-many-resources-pod
spec:
  containers:
  - args:
    - sh
    - -c
    - while true; do echo Running...; sleep 5; done
    image: busybox
    name: busybox
    resources:
      requests:
        memory: 64Mi
        cpu: 250m
      limits:
        memory: 200Mi
        cpu: 500m
