linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - revive
    - gosimple
    - lll
    - staticcheck
    - govet
    - goimports
    - gofmt
    - bodyclose
    - gocritic
    - tparallel
linters-settings:
  gocritic:
    disabled-checks:
      - captLocal
      - ifElseChain
