apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ckad-sc-pod
  name: ckad-sc-pod
spec:
  securityContext:
    runAsUser: 1000
    runAsNonRoot: false
    runAsGroup: 3000
    supplementalGroups: [3001, 3002]
    fsGroup: 2000
  containers:
  - image: busybox
    name: ckad-sc-pod
    command: ["sh", "-c", "while true; do sleep 10; done"]
    resources: {}
    securityContext:
      readOnlyRootFilesystem: false
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        add: ["NET_ADMIN", "SYS_TIME"]
        drop: ["NET_ADMIN"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
