apiVersion: v1
kind: Pod
metadata:
  name: securitycontext-pod
spec:
  containers:
  - args:
    - sh
    - -c
    - while true; do echo Running...; sleep 5; done
    image: busybox
    name: securitycontext-pod
    resources: {}
    securityContext:
      runAsUser: 3000
      runAsGroup: 4000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never
  
status: {}
