apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - name: first
    image: busybox
    command:
    - sh
    - -c
    - echo hello; sleep 3600
  - command:
    - sh
    - -c
    - echo hello; sleep 3600
    image: busybox
    name: second
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
