apiVersion: v1
kind: Pod
metadata:
  name: sidecar-test
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - while true; do echo 'The writer wrote this' > /output/log.txt; sleep 5; done
    image: busybox
    name: writer
    volumeMounts:
    - name: shared
      mountPath: /output
  - name: sidecar
    image: busybox
    args:
    - /bin/sh
    - -c
    - while true; do cat /input/log.txt; sleep 5; done
    volumeMounts:
    - name: shared
      mountPath: /input
  volumes:
    - name: shared
      emptyDir: {}
