Resources:
  EventStoreTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: ${self:custom.tablesDeletionPolicy.${self:provider.stage}, self:custom.tablesDeletionPolicy.default}
    Properties:
      TableName: ${self:provider.environment.TABLE_EVENT_STORE}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: version
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: ${self:custom.tablesBackup.${self:provider.stage}, self:custom.tablesBackup.default}