apiVersion: v1
kind: Service
metadata:
  name: bluegreen-test-svc
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bluegreen-test
    color: blue
  type: ClusterIP
