apiVersion: v1
kind: Pod
metadata:
  labels:
    app: client-pod
  name: client-pod
  namespace: test-b
spec:
  containers:
  - args:
    - sh
    - -c
    - while true; do curl -m 2 172.17.0.11; sleep 5; done
    image: radial/busyboxplus:curl
    name: client-pod
