apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-test
spec:
  rules:
  - host: ingresstest.acloud.guru
    http:
      paths:
      - backend:
          service:
            name: ingress-service
            port:
              number: 80
        path: /
        pathType: Prefix
