apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ingress-test
  name: ingress-pod
spec:
  containers:
  - image: nginx
    name: ingress-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
