apiVersion: v1
kind: Pod
metadata:
  labels:
    app: service-server
  name: service-server-pod
spec:
  containers:
  - image: nginx
    name: service-server-pod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
