apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-client-allow
  namespace: test-a
spec:
  podSelector:
    matchLabels:
      app: test-server
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          team: bteam
      podSelector:
        matchLabels:
          app: test-client
    ports:
    - protocol: TCP
      port: 80